substitutions:
  _REGION: "europe-west1"
steps:
  # Apply Cloud Deploy pipeline scaffolding
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "deploy", "apply",
        "--file", "clouddeploy.yaml",
        "--region", "${_REGION}",
        "--project", "$PROJECT_ID"
      ]
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/html-nginx/html-nginx:$BUILD_ID', '-f', 'Dockerfile']
    dir: 'app'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/html-nginx/html-nginx:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud artifacts docker images describe $_REGION-docker.pkg.dev/$PROJECT_ID/html-nginx/html-nginx:$BUILD_ID --format 'value(image_summary.digest)' > /workspace/sha
  # Create release in Google Cloud Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud deploy releases create rel-$BUILD_ID --delivery-pipeline "html-nginx-pipeline" --region ${_REGION} --images "html-nginx=${_REGION}-docker.pkg.dev/$PROJECT_ID/html-nginx/html-nginx@$(cat /workspace/sha)"
images: ['${_REGION}-docker.pkg.dev/$PROJECT_ID/html-nginx/html-nginx:$BUILD_ID']
options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
