apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: html-nginx
build:
  local: 
    push: false
  artifacts:
  - image: html-nginx
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: 
      - k8s/overlays/dev
portForward:
- resourceType: deployment
  resourceName: html-nginx
  port: 80 
  localPort: 80
profiles:
  - name: development
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/dev
  - name: prod
    deploy:
      kustomize:
        paths: 
          - k8s/overlays/prod