apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-nginx
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      containers:
          - name: html-nginx
