apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jeremy-ns-prod
resources:  # Use 'resources' instead of 'bases'
- ../../base
patches:  # Use 'patches' instead of 'patchesStrategicMerge'
- hpa.yaml
- deployment.yaml
- namespace.yaml 